enum actionTypes {
  SET_SETTINGS = 'SET_SETTINGS',
  SET_COLLECTIONS = 'SET_COLLECTIONS',
  SET_QUERY_INPUT = 'SET_QUERY_INPUT',
  ADD_QUERY_RESULT = 'ADD_QUERY_RESULT',
  CLEAR_QUERY_RESULT = 'CLEAR_QUERY_RESULT',
  START_QUERYING = 'START_QUERYING',
  END_QUERYING = 'END_QUERYING',
  SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE',
  HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE',
}

export default actionTypes;
