enum actionTypes {
  SET_SETTINGS,
  SET_COLLECTIONS,
  SET_QUERY_INPUT,
  ADD_QUERY_RESULT,
  CLEAR_QUERY_RESULT,
  START_QUERYING,
  STOP_QUERYING,
  SHOW_ERROR_MESSAGE,
  HIDE_ERROR_MESSAGE,
}

export default actionTypes;
